name: Augusto Paiva
description: Portfolio of Augusto Paiva
author: Augusto Paiva
analytics: UAXXXXXXXX1
exclude: [ _design, README ]
auto: true
markdown: rdiscount
permalink: caralho/:year/:month/:day/:title
rdiscount extensions: [smart]